[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ravi_hello"]

[project]
name = "ravi-hello"
version = "0.2.0"
description = "A simple hello module CLI tool"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [{ name = "Altar Ravi", email = "altarravik@gmail.com" }]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ravi-hello = "ravi_hello.main:main"