# pipeline:
  # - type: processors.snake.to_snakecase
  # - type: processors.upper.to_uppercase
pipeline:
  - type: processors.line_count.LineCountProcessor
  - type: processors.join_pairs.join_pairs

